config/routes.rb
Rails.application.routes.draw do
  root 'voice_checks#top'



    resources :voice_checks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :evaluators


  resources :staffs

  mount LetterOpenerWeb::Engine, at: '/inbox' if Rails.env.development?
end

app/models/staff.rb
class Staff < ApplicationRecord
   validates :staff_num,  presence: true, length: { maximum: 10 },uniqueness: true
   validates :release_time, length: { maximum:2 }

end

app/controllers/staffs_controller.rb
class StaffsController < ApplicationController
  before_action :set_staff, only: [:show, :edit, :update, :destroy]

  def index
    @staffs = Staff.all

  end

  def show
  end

  def new
    @staff = Staff.new
  end

  def edit
  end

  def create
    @staff = Staff.new(staff_params)

    respond_to do |format|
      if @staff.save
        format.html { redirect_to @staff, notice: '登録しました' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @staff.update(staff_params)
        format.html { redirect_to @staff, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @staff.destroy
    respond_to do |format|
      format.html { redirect_to staffs_url, notice: '削除しました' }
    end
  end

  private
    def set_staff
      @staff = Staff.find(params[:id])
    end

    def staff_params
      params.require(:staff).permit(:staff_num, :staff_name, :evaluation_cycle,:staff_area, :release_time)
    end
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/views/staffs/_form.html.erb
<%= form_with(model: staff, local: true) do |form| %>
<% if staff.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(staff.errors.count, "error") %>
      prohibited this staff from being saved:</h2>

    <ul>
      <% staff.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<br><br>
<div class="table-responsive">
  <table class="table">
    <tr>
      <th class="info">
        <%= form.label :スタッフID %></th>
      <th class="info">
        <%= form.label :地域 %></th>
      <th class="info">
        <%= form.label :リリース期 %></th>
      <th class="info">
        <%= form.label :スタッフ名 %></th>
      <th class="info">
        <%= form.label :評価サイクル %></th>
    </tr>

    <tr>
      <div class="field">
        <th>
          <%= form.text_field :staff_num, id: :staff_staff_num %></th>
      </div>

      <div class="field">
        <th><%= form.select :staff_area, [["北海道", "北海道"], ["東北", "東北"], ["関東", "関東"], ["東海", "東海"], ["甲信越", "甲信越"], ["関西", "関西"], ["中国", "中国"], ["四国", "四国"], ["九州", "九州"], ["沖縄", "沖縄"]],:include_blank => true %></th>
      </div>

      <div class="field">
        <th>
          <%= form.text_field :release_time, id: :staff_release_time %>期</th>
      </div>

      <div class="field">

        <th>
          <%= form.text_field :staff_name, id: :staff_staff_name %></th>
      </div>

      <div class="field">

        <!--%= form.number_field :evaluation_cycle, id: :staff_evaluation_cycle %-->
        <th><%= form.select :evaluation_cycle, [["1", "1"], ["3", "3"]],:include_blank => true %>ヶ月</th>
      </div>

    </table>
  </div>
</tbody>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>

app/views/staffs/edit.html.erb
<h2>Staff Edit</h2>

<%= render 'form', staff: @staff %>

<button class="btn-active" type="submit"><%= link_to '詳細', @staff %></button>
<button class="btn-active" type="submit"><%= link_to 'back', staffs_path %></button>

app/views/staffs/index.html.erb
<h2>Staff List</h2>

<td>
  <button btn-lg="btn-lg" class="btn-info btn-lg" type="submit"><%= link_to '新規登録', new_staff_path %></button>
</td>

<div class="table-responsive">
  <table class="table table-hover">
    <thead>
      <tr>
        <th>スタッフID</th>
        <th>地域</th>
        <th>リリース期</th>
        <th>スタッフ名</th>
        <th>評価サイクル</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @staffs.each do |staff| %>
        <tr>
          <th><%= staff.staff_num %></th>
          <th><%= staff.staff_area %></th>
          <th><%= staff.release_time %>期</th>
          <th><%= staff.staff_name %></th>
          <th><%= staff.evaluation_cycle %>ヶ月</th>
          <th>
            <button class="btn-success" type="submit"><%= link_to '詳細', staff %></button>
          </th>
          <th>
            <button class="btn-info" type="submit"><%= link_to '編集', edit_staff_path(staff) %></button>
          </th>
          <th>
            <button class="btn-danger" type="submit"><%= link_to '削除', staff, method: :delete, data: { confirm: '削除しますか?' } %></button>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</table>
</div>
<br>

app/views/staffs/new.html.erb
<h2>New staff</h2>

<%= render 'form', staff: @staff %>
<button class="btn-active" type="submit"><%= link_to 'Back', staffs_path %></button>

app/views/staffs/show.html.erb
<h2> スタッフ情報 ： <%= @staff.staff_name %>さん</h2>

<br><br>
<div class="table-responsive">
<table class="table table-bordered">
  <thead>
    <tr>
          <th class="info">スタッフID</th>
          <th class="info">地域 </th>
          <th class="info">リリース期 </th>
          <th class="info">スタッフ名</th>
          <th class="info">評価サイクル</th>
    </tr>
  </thead>

<th><%= @staff.staff_num %></th>
<th><%= @staff.staff_area %></th>
<th><%= @staff.release_time %>期</th>
<th><%= @staff.staff_name %></th>
<th><%= @staff.evaluation_cycle %>ヶ月</th>
</table>

</div>
<br>

<br>
<button class="btn-active" type="submit"><%= link_to '編集', edit_staff_path(@staff) %></button></td>
<button class="btn-active" type="submit"><%= link_to 'Back', staffs_path %></button></td><br>
<br>