config/routes.rb
Rails.application.routes.draw do
  root 'voice_checks#top'



    resources :voice_checks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :evaluators


  resources :staffs

  mount LetterOpenerWeb::Engine, at: '/inbox' if Rails.env.development?
end

app/models/voice_check.rb
class VoiceCheck < ApplicationRecord
 validates :staff_num,  presence: true, length: { maximum: 10 }
end

app/controllers/voice_checks_controller.rb
class VoiceChecksController < ApplicationController
  before_action :set_voice_check, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_evaluator!, only: [:new, :create]


  def index
    @voice_checks = VoiceCheck.all
  end


  def show
  end

  def new
    @voice_check = VoiceCheck.new
  end


  def edit
  end


  def create
    @voice_check = VoiceCheck.new(voice_check_params)

    respond_to do |format|
      if @voice_check.save
        format.html { redirect_to @voice_check, notice: '登録しました' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @voice_check.update(voice_check_params)
        format.html { redirect_to @voice_check, notice: '更新しました' }
      else
        format.html { render :edit }
      end
    end
  end


  def destroy
    @voice_check.destroy
    respond_to do |format|
      format.html { redirect_to voice_checks_url, notice: '削除しました' }
    end
  end


  private

    def set_voice_check
      @voice_check = VoiceCheck.find(params[:id])
    end


    def voice_check_params
      params.require(:voice_check).permit(:staff_num, :evaluator_id, :evaluator_name, :log_date, :log_time, :contact_details, :response_result, :evaluator_comment, :status, :customer_miss, :business_miss, :compliance_miss, :datetime, )
    end
end

app/helpers/voice_checks_helper.rb
module VoiceChecksHelper

end

app/views/voice_checks/_form.html.erb
<%= form_with(model: voice_check, local: true) do |form| %>
<% if voice_check.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(voice_check.errors.count, "error") %>
      prohibited this voice_check from being saved:</h2>
    <ul>
      <% voice_check.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>


<div class="table-responsive">
  <table class=table >
    <tr>
      <th class="info"><%= form.label :スタッフID %></th>
      <th class="info"><%= form.label :通話開始日時 %></th>
      <th class="info"><%= form.label :評価者%></th>
      <th class="info"><%= form.label :ステータス %></th>
    </tr>
    <div class="field" class="info">
      <!--%= form.text_field :staff_num, id: :voice_check_staff_num %-->
      <th><%= form.collection_select :staff_num, Staff.all.order(staff_num: :asc), :staff_num, :staff_num ,:include_blank => true%></th>
    </div>


    <div class="field">
      <th><%= form.datetime_select :datetime, id: :voice_check_datetime , :use_month_numbers => true %></th>

      </div>

      <div class="field">
        <th><!--%= form.select :evaluator_name, [["及川 恵美", "及川 恵美"], ["品質 花子", "品質 花子"], ["品質 太郎", "品質 花子"]] %-->
            <%= form.collection_select :evaluator_name, Evaluator.all, :name, :name ,:include_blank => true%></th>
      </div>

      <div class="field">
        <!--%= form.text_field :status, id: :voice_check_status %-->
        <th>
          <%= form.select :status, [["作成中", "作成中"], ["確定", "確定"]] %></th>
      </div>
    </table>
  </div>

  <!--%= form.label :評価者 %-->
  <!--%= form.text_field :evaluator_name, id: :voice_check_evaluator_name %-->

  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <th class="info"><%= form.label :お問い合わせ内容 %></th>
        <th class="info"><%= form.label :応対結果 %></th>
      </tr>
  <div class="field">
        <th><%= form.text_area :contact_details, id: :voice_check_contact_details %></th>
      </div>

      <div class="field">
        <th>
          <%= form.text_area :response_result, id: :voice_check_response_result %></th>
      </div>
    </table>
  </div>

  <div class="table-responsive">
    <table class="table table-bordered">
      <tr>
        <th class="info">ミス項目</th>
        <th class="info">ポイント</th>
        <th class="info">詳細</th>
        <th class="info">評価</th>
      </tr>

      <div class="field">
        <th><%= form.label :顧客の重大ミス %></th>
        <td>お客さまのご要望に応えること<br>マナーをもって対応すること</td>
        <td>・誤回答、誤案内、誤誘導がない
          <br>・著しいマナー不足がない<br>
        </td>
        <!--%= form.text_field :customer_miss, id: :voice_check_customer_miss %-->
        <th><%= form.select :customer_miss, [["◯", "◯"], ["✕", "✕"]],:include_blank => true %></th>
      </div>

      <tr>
        <div class="field">
          <th><%= form.label :ビジネスの重大ミス %></th>
          <td>収益に貢献すること<br>不必要なコストの発生がないこと<br/>
            <td>・不必要に対応時間を長引かせない
              <br>・業務損失、呼減に繫がる行為がない<br></td>

            <!--%= form.text_field :business_miss, id: :voice_check_business_miss %-->
            <th>
              <%= form.select :business_miss, [["◯", "◯"], ["✕", "✕"]], :include_blank => true %></th>
          </div>
        </tr>
        <tr>
          <div class="field">
            <th><%= form.label :コンプライアンスの重大ミス %></th>
            <td>個人情報を適切に取り扱うこと</td>
            <td>・本人性確認を正しく履行している</td>
            <!--%= form.text_field :compliance_miss, id: :voice_check_compliance_miss %-->
            <th><%= form.select :compliance_miss, [["◯", "◯"], ["✕", "✕"]],:include_blank => true %></th>
          </tr>
        </div>
      </table>

      <div class="table-responsive">
        <table class="table ">
          <tr>
            <th class="info"><%= form.label :評価者コメント %></th>
             <th class="info">登録</th>
          </tr>
          <div class="field">
            <th>
              <%= form.text_area :evaluator_comment, id: :voice_check_evaluator_comment %></th>
          </div>
          <div class="actions">
        <th><%= form.submit %></th>
          <% end %>
          </div>
        </table>
      </div>

app/views/voice_checks/edit.html.erb
<br>
<%= render 'form', voice_check: @voice_check %>
<button class="btn-active" type="submit"><%= link_to '詳細', @voice_check%></button>
<button class="btn-active" type="submit"><%= link_to '一覧', voice_checks_path %></button>

app/views/voice_checks/index.html.erb
<h2>Voice Check List</h2>
<td>
  <button btn-lg="btn-lg" class="btn-info btn-lg" type="submit"><%= link_to '新規作成', new_voice_check_path %></button>
</td>
<div class="table-responsive">
  <table class="table table-hover">

    <thead>
      <tr>
        <th>スタッフID</th>
        <th>評価者</th>
        <th>通話開始日時</th>
        <th>ステータス</th>
        <th>顧客のミス</th>
        <th>ビジネスミス</th>
        <th>コンプラミス</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @voice_checks.each do |voice_check| %>
        <tr>
          <th><%= voice_check.staff_num %></th>
          <th><%= voice_check.evaluator_name %></th>

          <th>
            <% if voice_check.datetime.present? %>
              <%= voice_check.datetime.strftime('%Y/%m/%d %R') %>
            <% else %>
              <%= nil%>
            <% end %>
          </th>

          <th>
            <p class="text-danger"><%= voice_check.status %></p>
          </th>
          <th><%= voice_check.customer_miss %></th>
          <th><%= voice_check.business_miss %></th>
          <th><%= voice_check.compliance_miss %></th>
          <th>
            <button class="btn-success" type="submit"><%= link_to '詳細', voice_check %></button>
          </th>
          <th>
            <button class="btn-info" type="submit"><%= link_to '編集', edit_voice_check_path(voice_check) %></button>
          </th>
          <th>
            <button class="btn-danger" type="submit"><%= link_to '削除', voice_check, method: :delete, data: { confirm: '削除しますか?' } %></button>
          </th>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/voice_checks/new.html.erb
<h2>New Voice Check</h2>

<%= render 'form', voice_check: @voice_check %>

<button class="btn-active" type="submit"><%= link_to 'Back', voice_checks_path %></button>

app/views/voice_checks/show.html.erb
<br>
<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <th class="info">スタッフ番号</th>
      <th class="info">通話開始日時</th>
      <th class="info">評価者</th>
      <th class="info">ステータス</th>
    </tr>
    <div class="info">
      <th>
        <%= @voice_check.staff_num %></th>
    </div>

    <div class="field">
      <th>
      <% if @voice_check.datetime.present? %>
      <%=   @voice_check.datetime.strftime('%Y/%m/%d %R') %>
      <% else %>
      <%=  nil%>
        <% end %>
      </th>
    </div>

    <div class="field">
      <th>
        <%= @voice_check.evaluator_name %></th>

    </div>

    <div class="field">
      <!--%= form.text_field :status, id: :voice_check_status %-->
      <th>
        <%= @voice_check.status %></th>
    </div>
  </table>
</div>

<!--%= form.label :評価者 %-->
<!--%= form.text_field :evaluator_name, id: :voice_check_evaluator_name %-->

<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <th class="info">お問い合わせ内容</th>
      <th class="info">応対結果</th>
    </tr>
    <div class="field">
      <th>
        <%= @voice_check.contact_details %></th>
    </div>

    <div class="field">
      <th>
        <%= @voice_check.response_result %></th>
    </div>
  </table>
</div>

<div class="table-responsive">
  <table class="table table-bordered">
    <tr>
      <th class="info">ミス項目</th>
      <th class="info">ポイント</th>
      <th class="info">詳細</th>
      <th class="info">評価</th>
    </tr>

    <div class="field">
      <th>顧客の重大ミス</th>
      <td>お客さまのご要望に応えること<br>マナーをもって対応すること</td>
      <td>・誤回答、誤案内、誤誘導がない
        <br>・著しいマナー不足がない<br>
      </td>
      <!--%= form.text_field :customer_miss, id: :voice_check_customer_miss %-->
      <th>
        <%= @voice_check.customer_miss %></th>
    </div>

    <tr>
      <div class="field">
        <th>ビジネスの重大ミス</th>
        <td>収益に貢献すること<br>不必要なコストを発生させないこと<br/>
          <td>・不必要に対応時間を長引かせない
            <br>・業務損失、呼減につながる行為がない<br></td>

          <!--%= form.text_field :business_miss, id: :voice_check_business_miss %-->
          <th>
            <%= @voice_check.business_miss %></th>
        </div>
      </tr>
      <tr>
        <div class="field">
          <th>コンプライアンスの重大ミス</th>
          <td>個人情報を適切に取り扱うこと</td>
          <td>・本人性確認を正しく履行している</td>
          <!--%= form.text_field :compliance_miss, id: :voice_check_compliance_miss %-->
          <th>
            <%= @voice_check.compliance_miss %></th>
        </tr>
      </div>
    </table>

    <table class="table table-bordered">
      <tr>
        <th class="info">評価者コメント</th>
      </tr>
      <div class="field">
        <th>
          <%= @voice_check.evaluator_comment %></th>
      </div>

    </table>
  </div>

  <br>
  <button class="btn-active" type="submit"><%= link_to '編集', edit_voice_check_path(@voice_check) %></button>
</th>
<th>
  <button class="btn-active" type="submit"><%= link_to '一覧', voice_checks_path %></button>
</th>

app/views/voice_checks/top.html.erb
<header class="jumbotron text-center">
  <div class="container">

    <h1 class="jumbotron-h1">voice check</h1>

    <% if evaluator_signed_in? %>
      <span><%=link_to '評価一覧', voice_checks_path, class: 'btn-lg btn-default' %></span>
    <% else %>
      <span><%= link_to "新規登録", new_evaluator_registration_path, class: 'btn-lg btn-default' %></span>
      <span><%= link_to " ログイン", new_evaluator_session_path, class: 'btn-lg btn-default' %></span>
    <% end %>
  </div>
</header>