config/routes.rb
Rails.application.routes.draw do
  root 'voice_checks#top'



    resources :voice_checks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :evaluators


  resources :staffs

  mount LetterOpenerWeb::Engine, at: '/inbox' if Rails.env.development?
end

app/models/voice.rb
class Voice < ApplicationRecord

end

app/controllers/voices_controller.rb
class VoicesController < ApplicationController
  before_action :set_voice, only: %i[show edit update destroy]
  before_action :authenticate_evaluator!, only: [:new, :create]


  def index
    @voices = Voice.all
  end

  def show; end

  def new
    @voice = Voice.new
  end

  def edit; end

  def create
    @voice = Voice.new(voice_params)


    respond_to do |format|
      if @voice.save
        format.html { redirect_to @voice, notice: 'Voice was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def update
    respond_to do |format|
      if @voice.update(voice_params)
        format.html { redirect_to @voice, notice: 'Voice was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @voice.destroy
    respond_to do |format|
      format.html { redirect_to voices_url, notice: 'Voice was successfully destroyed.' }
    end
  end


  private

  def set_voice
    @voice = Voice.find(params[:id])
  end

  def voice_params
    params.require(:voice).permit(:staff_num, :evaluator_id, :year_month, :contact_details, :response_result, :evaluator_comment, :score, :rank, :status, :item_one, :item_two, :item_three, :item_four, :item_five)
  end
end

app/views/voices/_form.html.erb
<%= form_with(model: voice, local: true) do |form| %>
<% if voice.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(voice.errors.count, "error") %>
      prohibited this voice from being saved:</h2>

    <ul>
      <% voice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>



<div class="field">
  <%= form.label :スタッフID %>
  <%= form.text_field :staff_num, id: :voice_staff_num %>
</div>



<div class="field">
  <%= form.label :evaluator_id %>
  <%= form.number_field :evaluator_id, id: :voice_evaluator_id %>
</div>

<div class="field">
  <%= form.label :evaluator_name %>
  <%= form.number_field :evaluator_name, id: :voice_evaluator_name %>
</div>

<div class="field">
  <%= form.label :評価月 %>
  <%= form.text_field :year_month, id: :voice_year_month %>
  <%= form.date_field :year_month, id: :voice_year_month %>
</div>

<div class="field">
  <%= form.label :ログ月日 %>
  <%= form.text_field :log_date, id: :voice_log_date %>
</div>

<div class="field">
  <%= form.label :通話開始時間 %>
  <%= form.text_field :log_time, id: :log_time %>
</div>


<div class="field">
  <%= form.label :問い合わせ内容 %>
  <%= form.text_field :contact_details, id: :voice_contact_details %>
</div>

<div class="field">
  <%= form.label :応対結果 %>
  <%= form.text_field :response_result, id: :voice_response_result %>
</div>

<div class="field">
  <%= form.label :評価者コメント %>
  <%= form.text_field :evaluator_comment, id: :voice_evaluator_comment %>
</div>

<div class="field">
  <%= form.label :点数 %>
  <%= form.number_field :score, id: :voice_score %>
</div>

<div class="field">
  <%= form.label :ランク %>
  <%= form.text_field :rank, id: :voice_rank %>
</div>

<div class="field">
  <%= form.label :ステータス %>
  <%= form.number_field :status, id: :voice_status %>
</div>

<div class="field">
  <%= form.label :項番1 %>
  <%= form.select :item_one, [["○", "1"], ["✕", "０"]],:include_blank => true %>
</div>
</div>

<div class="field">
  <%= form.label :項番2 %>
  <%= form.select :item_two, [["○", "1"], ["✕", "０"]],:include_blank => true %>
</div>
</div>

<div class="field">
  <%= form.label :項番3 %>
  <%= form.select :item_three, [["○", "1"], ["✕", "０"]],:include_blank => true %>
</div>

<div class="field">
  <%= form.label :項番4 %>
  <%= form.select :item_four, [["○", "1"], ["✕", "０"]],:include_blank => true %>
</div>

<div class="field">
  <%= form.label :項番5 %>
  <%= form.select :item_five, [["○", "1"], ["✕", "０"]],:include_blank => true %>
</div>

<div class="field">
  <%= form.label :顧客の重大ミス %>
  <%= form.select :customer_miss, [["○", "○"], ["✕", "✕"]],:include_blank => true %>
</div>

<div class="field">
  <%= form.label :ビジネスの重大ミス %>
  <%= form.select :business_miss, [["○", "○"], ["✕", "✕"]],:include_blank => true %>
</div>

<div class="field">
  <%= form.label :コンプライアンスの重大ミス %>
  <%= form.select :compliance_miss, [["○", "○"], ["✕", "✕"]],:include_blank => true %>
</div>

<div class="actions">
  <%= form.submit %>
</div>
<% end %>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
        <span class="sr-only">Bootstrap</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Bootstrap

      </a>
    </div>
    <div id="gnavi" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="">top</a></li>
        <li><a href="">menu1</a></li>
        <li><a href="">menu2</a></li>
      </ul>
    </div>
  </div>
</nav>

app/views/voices/edit.html.erb
<h1>Editing Voice</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Show', @voice %> |
<%= link_to 'Back', voices_path %>

app/views/voices/index.html.erb
<% if current_evaluator.try(:admin?) %>
  <h1>Evaluators_admin</h1>
<% else %>
  <h1>Evaluators</h1>
<% end %>

<h1>評価一覧</h1>

<table>
  <thead>
    <tr>
      <th>スタッフID</th>
      <th>評価者</th>
      <th>評価月</th>

      <th>点数</th>
      <th>ランク</th>
      <th>ステータス</th>

      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @voices.each do |voice| %>
      <tr>
        <td><%= voice.staff_num %></td>

        <td><%= voice.evaluator_id %></td>
        <td><%= voice.evaluator_name %></td>
        <td><%= voice.year_month %></td>
        <td><%= voice.score %></td>
        <td><%= voice.rank %></td>
        <td><%= voice.status %></td>

        <td><%= voice.customer_miss %></td>
        <td><%= voice.business_miss %></td>
        <td><%= voice.compliance_miss %></td>

        <td><%= link_to 'Show', voice %></td>
        <td><%= link_to 'Edit', edit_voice_path(voice) %></td>
        <td><%= link_to 'Destroy', voice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Voice', new_voice_path %>

app/views/voices/new.html.erb
<h1>新規作成</h1>

<%= render 'form', voice: @voice %>

<%= link_to 'Back', voices_path %>

app/views/voices/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>スタッフID:</strong>
  <%= @voice.staff_num %>
</p>

<p>
  <strong>評価者:</strong>
  <%= @voice.evaluator_id %>
</p>

<p>
  <strong>評価月:</strong>
  <%= @voice.year_month %>
</p>

<p>
  <strong>問い合わせ内容:</strong>
  <%= @voice.contact_details %>
</p>

<p>
  <strong>応対結果:</strong>
  <%= @voice.response_result %>
</p>

<p>
  <strong>評価者コメント:</strong>
  <%= @voice.evaluator_comment %>
</p>

<p>
  <strong>点数:</strong>
  <%= @voice.score %>
</p>

<p>
  <strong>ランク:</strong>
  <%= @voice.rank %>
</p>

<p>
  <strong>ステータス:</strong>
  <%= @voice.status %>
</p>

<p>
  <strong>項番1:</strong>
  <%= @voice.item_one %>
</p>

<p>
  <strong>項番2:</strong>
  <%= @voice.item_two %>
</p>

<p>
  <strong>項番3:</strong>
  <%= @voice.item_three %>
</p>

<p>
  <strong>項番4:</strong>
  <%= @voice.item_four %>
</p>

<p>
  <strong>項番5:</strong>
  <%= @voice.item_five %>
</p>

<%= link_to 'Edit', edit_voice_path(@voice) %> |
<%= link_to 'Back', voices_path %>