config/routes.rb
Rails.application.routes.draw do
  root 'voice_checks#top'



    resources :voice_checks
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :evaluators


  resources :staffs

  mount LetterOpenerWeb::Engine, at: '/inbox' if Rails.env.development?
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ボイスログ評価管理システム</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <meta name="viewport" content="width=device-width,initial-scale=1">
  </head>

  <body>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <ul class="navbar-brand" href="#"><%= link_to "ボイスログ評価管理システム", root_path %></ul>
        </div>

        <div id="navbar" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <li class="default">

              <% if evaluator_signed_in? %>
              <li><%= link_to '評価新規作成', new_voice_check_path %></li>
              <li><%= link_to "評価一覧", voice_checks_path %></li>
              <li><%= link_to 'スタッフ新規登録', new_staff_path %></li>
              <li><%= link_to "スタッフ一覧", staffs_path %></li>
              <li><%= link_to "管理画面", "https://stormy-shore-37000.herokuapp.com/admin" %></li>
            </li>
          </ul>

          <p class="navbar-text navbar-right">
            <span><%= link_to "ログアウト", destroy_evaluator_session_path, method: :delete %></span></p>

          <p class="navbar-text navbar-right">
            <span>ようこそ
              <strong><%= link_to current_evaluator.name, voice_checks_path(current_evaluator.id) %></strong>
              さん</span></p>

        <% else %>

          <p class="navbar-text navbar-right">
            <span><%= link_to "新規登録", new_evaluator_registration_path %></span></p>

          <p class="navbar-text navbar-right">
            <span>
              <%= link_to "ログイン", new_evaluator_session_path %></span></p>
        </div>
      <% end %>
    </div>
  </nav>
  <!--/.nav-collapse -->
  <% if notice %>
    <p class="alert alert-notice"><%= notice %></p>
  <% end %>
  <% if alert %>
    <p class="alert alert-error"><%= alert %></p>
  <% end %>

   <%= yield %>

  <footer class="footer">
    <div class="container">
      <p class="text-muted">NTT ComCHEO 2018 oikawa emi
      </p>
    </div>
  </footer>

 </body>
</html>